import { createHash } from "node:crypto";
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync, utimesSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { describe, expect, it } from "vitest";

const sha = (path: string) => createHash("sha256").update(readFileSync(path)).digest("hex");
const jsonSha = (value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex");
const write = (path: string, value: unknown) => writeFileSync(path, typeof value === "string" ? value : JSON.stringify(value));

describe("隔离视觉审核入口", () => {
  it("要求构图前的参考预检，并将审核包与当前工件绑定", () => {
    const dir = mkdtempSync(join(tmpdir(), "visual-review-entry-"));
    const paths = Object.fromEntries(["scene", "png", "phone", "content", "positive", "negative", "taste", "tokens", "gates", "protocol", "preflight", "pagecheck", "packet"].map((name) => [name, join(dir, `${name}.json`)])) as Record<string, string>;
    write(paths.content, "content"); write(paths.positive, "positive"); write(paths.negative, "negative");
    write(paths.taste, "taste"); write(paths.tokens, JSON.parse(readFileSync("design_tokens.json", "utf8"))); write(paths.gates, "gates"); write(paths.protocol, "protocol");
    write(paths.png, "png"); write(paths.phone, "phone");
    const refs = [paths.positive, paths.negative].map((path) => ({ path: resolve(path), sha256: sha(path), observed: "观察到具体对象状态承担解释", effect_on_page: "本页以具体动作表达内容关系" }));
    write(paths.preflight, { status: "completed_before_construction", page_id: "P01", role: "overview", content_sha256: sha(paths.content), taste_sha256: sha(paths.taste), design_tokens_sha256: sha(paths.tokens), references: refs, main_visual_explanation: "具体物件的前后状态解释核心判断", reading_path: "从标题到主图再到边界结论", module_relations: [{ from: "页面问题区域", to: "具体案例区域", relation_type: "主张与来源案例的例证关系", reader_question: "这个主张能从哪个案例看清", forbidden_reading: "不能把一个案例推成普遍规律" }], text_graphic_split: "图形承担动作关系，文字承载证据边界", mobile_type_plan: "正文保持手机整页可读字号", color_role_plan: { ink: "正文色承担论点和证据", primary: "主色引导关键层级", accent: "辅色标出本期的选择", weak: "弱化色只承担辅助来源" }, forbidden_patterns: ["禁用没有解释力的通用空框和箭头"] });
    write(paths.scene, { elements: [], files: {} });
    const passCheck = { status: "pass", visible_evidence: "当前图片中可定位的具体检查结果" };
    write(paths.pagecheck, { page_id: "P01", scene_sha256: sha(paths.scene), png_sha256: sha(paths.png), status: "submitted_for_independent_review", checks: Object.fromEntries(["content_coverage", "visual_explanation", "reference_alignment", "text_geometry", "mobile_readability"].map((name) => [name, passCheck])) });
    const earlier = new Date(Date.now() - 5000), later = new Date();
    utimesSync(paths.preflight, earlier, earlier); utimesSync(paths.scene, later, later);
    const command = ["scripts/prepare_independent_review.py", "--page-id", "P01", "--role", "overview", "--creator-context-id", "creator-agent", "--scene", paths.scene, "--png", paths.png, "--phone", paths.phone, "--content", paths.content, "--positive", paths.positive, "--negative", paths.negative, "--taste", paths.taste, "--design-tokens", paths.tokens, "--preflight", paths.preflight, "--page-check", paths.pagecheck, "--design-gates", paths.gates, "--review-protocol", paths.protocol, "--output", paths.packet];
    const run = () => spawnSync("python3", command, { cwd: resolve("."), encoding: "utf8" });
    const first = run();
    expect(first.status, first.stderr).toBe(0);
    expect(JSON.parse(readFileSync(paths.packet, "utf8")).preflight_sha256).toBe(sha(paths.preflight));
    const prepared = JSON.parse(readFileSync(paths.packet, "utf8"));
    const colorAsset = prepared.standards.color_role_plan;
    expect(colorAsset.sha256).toBe(sha(colorAsset.path));
    expect(JSON.parse(readFileSync(colorAsset.path, "utf8")).weak).toBe("弱化色只承担辅助来源");
    // 验证实际 prepare 的输出可直接进入现有 closeout。
    mkdirSync(join(dir, "04-rendered"));
    const gray = join(dir, "gray.png"); write(gray, "gray");
    const manifest = { schema_version: "1.0", kind: "render_manifest", status: "completed", scene_manifest_sha256: "0".repeat(64), pages: [{ page_id: "P01", scene_sha256: sha(paths.scene), png: paths.png, png_sha256: sha(paths.png), phone_png: paths.phone, phone_png_sha256: sha(paths.phone), grayscale_png: gray, grayscale_png_sha256: sha(gray) }], created_at: new Date().toISOString() };
    write(join(dir, "04-rendered", "render_manifest.json"), manifest);
    const reviewPath = join(dir, "review.json");
    const closeout = () => {
      write(reviewPath, { schema_version: "1.0", kind: "independent_visual_review", status: "completed", render_manifest_sha256: jsonSha(manifest), reviewer_context: "isolated_read_only", reviewer_context_id: "test-independent-agent", pages: [{ page_id: "P01", png_sha256: sha(paths.png), review_packet_sha256: sha(paths.packet), verdict: "TARGET", findings: [] }], reviewed_at: new Date().toISOString() });
      return spawnSync("node", ["dist/visual-closeout-cli.js", "--workspace", dir, "--review", reviewPath, "--packet", paths.packet, "--action", "submit"], { cwd: resolve("."), encoding: "utf8" });
    };
    expect(closeout().status).toBe(0);
    write(colorAsset.path, { changed: true });
    expect(closeout().stderr).toContain("隔离审核输入文件已变化或缺失");
    expect(run().status).toBe(0);

    // 冻结复核不声称创作前预检，且必须精确匹配原验收的四工件。
    const priorApproval = join(dir, "approval.json");
    const current = Object.fromEntries([["scene", paths.scene], ["png", paths.png], ["phone", paths.phone], ["gray", gray]].map(([key, path]) => [key, { path, sha256: sha(path) }]));
    write(priorApproval, { page_id: "P01", user_accepted: true, current });
    const frozenPreflight = JSON.parse(readFileSync(paths.preflight, "utf8"));
    frozenPreflight.status = "completed_before_existing_artwork_review";
    write(paths.preflight, frozenPreflight);
    write(paths.pagecheck, JSON.parse(readFileSync(paths.pagecheck, "utf8")));
    const frozenRun = () => spawnSync("python3", [...command, "--revalidate-existing", "--prior-approval", priorApproval, "--gray", gray], { cwd: resolve("."), encoding: "utf8" });
    expect(frozenRun().status).toBe(0);
    expect(JSON.parse(readFileSync(paths.packet, "utf8")).review_mode).toBe("frozen_existing_artwork_revalidation");
    expect(run().status).not.toBe(0);
    write(priorApproval, { page_id: "P01", user_accepted: false, current });
    expect(frozenRun().stderr).toContain("缺少明确的原始用户验收");
    write(priorApproval, { page_id: "P01", user_accepted: true, current });
    write(gray, "changed gray");
    expect(frozenRun().stderr).toContain("冻结复核工件与原始用户验收不一致：gray");
    write(gray, "gray");
    const failedFrozenCheck = JSON.parse(readFileSync(paths.pagecheck, "utf8"));
    failedFrozenCheck.checks.visual_explanation.status = "fail";
    write(paths.pagecheck, failedFrozenCheck);
    expect(frozenRun().stderr).toContain("成图自检未通过：visual_explanation");
    failedFrozenCheck.checks.visual_explanation.status = "pass";
    write(paths.pagecheck, failedFrozenCheck);
    frozenPreflight.status = "completed_before_construction";
    write(paths.preflight, frozenPreflight);
    const future = new Date(Date.now() + 5000);
    utimesSync(paths.preflight, future, future);
    expect(run().stderr).toContain("联合预检文件晚于当前 scene");
    utimesSync(paths.preflight, earlier, earlier);
    const badPreflight = JSON.parse(readFileSync(paths.preflight, "utf8"));
    delete badPreflight.module_relations;
    write(paths.preflight, badPreflight);
    utimesSync(paths.preflight, earlier, earlier);
    expect(run().stderr).toContain("联合预检缺少页内模块关系");
    badPreflight.module_relations = [{ from: "页面问题区域", to: "具体案例区域", relation_type: "主张与来源案例的例证关系", reader_question: "这个主张能从哪个案例看清", forbidden_reading: "不能把一个案例推成普遍规律" }];
    write(paths.preflight, badPreflight);
    utimesSync(paths.preflight, earlier, earlier);
    delete badPreflight.color_role_plan;
    write(paths.preflight, badPreflight);
    utimesSync(paths.preflight, earlier, earlier);
    expect(run().stderr).toContain("联合预检缺少本期颜色职责表");
    badPreflight.color_role_plan = { ink: "正文色承担论点和证据", primary: "主色引导关键层级", accent: "辅色标出本期的选择", weak: "弱化色只承担辅助来源" };
    write(paths.preflight, badPreflight);
    utimesSync(paths.preflight, earlier, earlier);
    const badCheck = JSON.parse(readFileSync(paths.pagecheck, "utf8"));
    badCheck.checks.visual_explanation.status = "fail";
    write(paths.pagecheck, badCheck);
    expect(run().stderr).toContain("成图自检未通过：visual_explanation");
    badCheck.checks.visual_explanation.status = "pass";
    write(paths.pagecheck, badCheck);
    write(paths.taste, "changed taste");
    expect(run().stderr).toContain("联合预检与当前输入不一致：taste_sha256");
  });

  it("closeout 拒绝没有对应审核包的 TARGET 报告", () => {
    const dir = mkdtempSync(join(tmpdir(), "visual-closeout-entry-"));
    mkdirSync(join(dir, "04-rendered"));
    const scene = join(dir, "page.excalidraw"), png = join(dir, "page.png"), phone = join(dir, "phone.png"), gray = join(dir, "gray.png"), content = join(dir, "content.json"), taste = join(dir, "taste.md");
    [scene, png, phone, gray, content, taste].forEach((path) => write(path, path));
    const zero = "0".repeat(64), page = { page_id: "P01", scene_sha256: sha(scene), png: "page.png", png_sha256: sha(png), phone_png: "phone.png", phone_png_sha256: sha(phone), grayscale_png: "gray.png", grayscale_png_sha256: sha(gray) };
    const manifest = { schema_version: "1.0", kind: "render_manifest", status: "completed", scene_manifest_sha256: zero, pages: [page], created_at: new Date().toISOString() };
    write(join(dir, "04-rendered", "render_manifest.json"), manifest);
    const packetPath = join(dir, "packet.json");
    write(packetPath, { kind: "independent_visual_review_packet", page_id: "P01", creator_context_id: "creator-agent", current: { scene: { path: scene, sha256: sha(scene) }, png: { path: png, sha256: sha(png) }, phone: { path: phone, sha256: sha(phone) } }, content: { path: content, sha256: sha(content) }, positive: [], negative: [], standards: { taste: { path: taste, sha256: sha(taste) } }, preflight_sha256: zero, rendered_page_check_sha256: zero });
    const reviewPath = join(dir, "review.json");
    write(reviewPath, { schema_version: "1.0", kind: "independent_visual_review", status: "completed", render_manifest_sha256: jsonSha(manifest), reviewer_context: "isolated_read_only", reviewer_context_id: "independent-agent", pages: [{ page_id: "P01", png_sha256: sha(png), review_packet_sha256: zero, verdict: "TARGET", findings: [] }], reviewed_at: new Date().toISOString() });
    const result = spawnSync("node", ["dist/visual-closeout-cli.js", "--workspace", dir, "--review", reviewPath, "--packet", packetPath, "--action", "approve", "--user-approved"], { cwd: resolve("."), encoding: "utf8" });
    expect(result.status).not.toBe(0);
    expect(result.stderr).toContain("隔离审核输入包与当前 scene、PNG、预检、自检或审核报告不匹配");
  });
});
